/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.AlumnoControlador;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan De la Rosa
 */
public class FormFiltrarAlumnos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormFiltrarAlumnos.class.getName());
    private FormAlumnosS Form1;
    private FormAlumnosD Form2;
    /**
     * Creates new form FormFiltrarAlumnos
     */
    public FormFiltrarAlumnos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by te Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Grupo_tb = new javax.swing.JTextField();
        Filtrar_bt = new javax.swing.JButton();
        Cerrar_bt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombre_maestro = new java.awt.TextField();
        grupo_n = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        materias_tb = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_bt = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ESC. PRIM. Arcoiris");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Datos del alumno: ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texto.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filtrado de alumnos");
        setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grupo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Grupo_tb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Grupo_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grupo_tbActionPerformed(evt);
            }
        });
        getContentPane().add(Grupo_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 50, -1));

        Filtrar_bt.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Filtrar_bt.setText("Filtrar");
        Filtrar_bt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Filtrar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtrar_btActionPerformed(evt);
            }
        });
        getContentPane().add(Filtrar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, -1));

        Cerrar_bt.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Cerrar_bt.setText("Cerrar");
        Cerrar_bt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cerrar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_btActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Docente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        nombre_maestro.setEditable(false);
        getContentPane().add(nombre_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 260, 20));

        grupo_n.setEditable(false);
        grupo_n.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        grupo_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupo_nActionPerformed(evt);
            }
        });
        getContentPane().add(grupo_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 50, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Materias:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 80, 40));

        jScrollPane2.setViewportView(materias_tb);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 200, 150));

        tabla_bt.setAutoCreateRowSorter(true);
        tabla_bt.setBackground(new java.awt.Color(153, 204, 255));
        tabla_bt.setBorder(new javax.swing.border.MatteBorder(null));
        tabla_bt.setFont(new java.awt.Font("Segoe UI Light", 3, 12)); // NOI18N
        tabla_bt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_bt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 340, 160));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Alumnos Ingresados");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 380));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texto.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -30, 900, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void FiltrarAlumnos(Connection conexion, 
                           javax.swing.JTable tabla_bt, 
                           javax.swing.JTextField Grupo_tb, 
                           java.awt.TextField grupo_n, 
                           java.awt.TextField nombre_maestro,
                           javax.swing.JList<String> materias_tb) {
    String grupoTexto = Grupo_tb.getText().trim();

    if (grupoTexto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un grupo para filtrar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Consulta SQL para obtener alumnos y datos del maestro del grupo
        String sqlAlumnos = "SELECT a.nombre, a.apellido, a.curp, g.nombre_maestro, g.apellido_maestro, g.idPaqueteMaterias " +
                            "FROM alumnos a " +
                            "INNER JOIN grupos g ON a.id_grupo = g.id_grupo " +
                            "WHERE g.grupo = ? " +
                            "ORDER BY a.apellido ASC";

        try (PreparedStatement ps = conexion.prepareStatement(sqlAlumnos)) {
            ps.setString(1, grupoTexto);
            ResultSet rs = ps.executeQuery();

            // Modelo de tabla para los alumnos
            javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
            modelo.addColumn("No.Lista");
            modelo.addColumn("Apellidos");
            modelo.addColumn("Nombre");
            modelo.addColumn("CURP");

            int contador = 1;
            String nombreMaestro = "";
            String apellidoMaestro = "";
            int idPaqueteMaterias = -1; // ID del paquete de materias del grupo

            while (rs.next()) {
                if (nombreMaestro.isEmpty() && apellidoMaestro.isEmpty()) {
                    nombreMaestro = rs.getString("nombre_maestro");
                    apellidoMaestro = rs.getString("apellido_maestro");
                    idPaqueteMaterias = rs.getInt("idPaqueteMaterias");
                }

                modelo.addRow(new Object[]{
                    contador,
                    rs.getString("apellido"),
                    rs.getString("nombre"),
                    rs.getString("curp")
                });
                contador++;
            }

            if (modelo.getRowCount() == 0) {
                modelo.addRow(new Object[]{"-", "No se encontraron alumnos", "-", "-"});
            }

            // Asignar modelo a la tabla
            tabla_bt.setModel(modelo);
            tabla_bt.setShowGrid(true);
            tabla_bt.setGridColor(java.awt.Color.GRAY);
            tabla_bt.setFillsViewportHeight(true);

            // Mostrar el grupo y nombre del maestro
            grupo_n.setText(grupoTexto);
            nombre_maestro.setText((nombreMaestro.isEmpty() ? "" : nombreMaestro + " " + apellidoMaestro));

            // Ahora cargamos las materias del grupo
            DefaultListModel<String> modeloMaterias = new DefaultListModel<>();
            if (idPaqueteMaterias != -1) {
                String sqlMaterias = "SELECT materia1, materia2, materia3, materia4, materia5, materia6, materia7, materia8 " +
                                     "FROM paquetematerias WHERE id = ?";
                try (PreparedStatement psMat = conexion.prepareStatement(sqlMaterias)) {
                    psMat.setInt(1, idPaqueteMaterias);
                    ResultSet rsMat = psMat.executeQuery();
                    if (rsMat.next()) {
                        for (int i = 1; i <= 8; i++) {
                            String materia = rsMat.getString("materia" + i);
                            if (materia != null && !materia.isEmpty()) {
                                modeloMaterias.addElement(materia);
                            }
                        }
                    }
                }
            }

            materias_tb.setModel(modeloMaterias);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al filtrar los alumnos o materias: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    }
}







    private void Filtrar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtrar_btActionPerformed
        AlumnoControlador ObjAlumnoControlador = new AlumnoControlador();
    FiltrarAlumnos(FormLogin.conexionGlobal.IniciarConexion(), tabla_bt, Grupo_tb,grupo_n,nombre_maestro, materias_tb );
    }//GEN-LAST:event_Filtrar_btActionPerformed

    private void Cerrar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_btActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Cerrar_btActionPerformed

    private void Grupo_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grupo_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grupo_tbActionPerformed

    private void grupo_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupo_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupo_nActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void setForm1(FormAlumnosS Form1)
    {
        this.Form1 = Form1;
    }
    public void setForm2(FormAlumnosD Form2)
    {
        this.Form2 = Form2;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormFiltrarAlumnos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar_bt;
    private javax.swing.JButton Filtrar_bt;
    private javax.swing.JTextField Grupo_tb;
    private java.awt.TextField grupo_n;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> materias_tb;
    private java.awt.TextField nombre_maestro;
    private javax.swing.JTable tabla_bt;
    // End of variables declaration//GEN-END:variables

    void setForm3(FormAlumnosD aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
