/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.sql.SQLException;
import static vistas.FormLogin.conexionGlobal;
import vistas.FormFiltrarAlumnos;


/**
 *
 * @author Ivan De la Rosa
 */
public class FormMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenu.class.getName());
    private FormLogin FormLogin;
    

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        if(conexionGlobal.RegresarUsuario().matches("^((?!director).)*$"))
        {
            Secretarios_bt.setVisible(false);
            Respaldo_.setVisible(false);
            Bitacora.setVisible(false);
            jLabel2.setVisible(false);
            
        }
        else{
            jLabel5.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Generar_bt = new javax.swing.JButton();
        Alumnos_bt = new javax.swing.JButton();
        Secretarios_bt = new javax.swing.JButton();
        Volver_bt = new javax.swing.JButton();
        Bitacora = new javax.swing.JButton();
        Lista_Trimestral = new javax.swing.JButton();
        Datos_Estadisticos_ = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Respaldo_ = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 70));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Generar_bt.setBackground(new java.awt.Color(0, 51, 153));
        Generar_bt.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Generar_bt.setForeground(new java.awt.Color(255, 255, 255));
        Generar_bt.setText("Boletas");
        Generar_bt.setBorder(new javax.swing.border.MatteBorder(null));
        Generar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar_btActionPerformed(evt);
            }
        });
        getContentPane().add(Generar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 150, 30));

        Alumnos_bt.setBackground(new java.awt.Color(0, 51, 153));
        Alumnos_bt.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Alumnos_bt.setForeground(new java.awt.Color(255, 255, 255));
        Alumnos_bt.setText("Registrar alumno");
        Alumnos_bt.setToolTipText("");
        Alumnos_bt.setBorder(new javax.swing.border.MatteBorder(null));
        Alumnos_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alumnos_btActionPerformed(evt);
            }
        });
        getContentPane().add(Alumnos_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 150, 30));

        Secretarios_bt.setBackground(new java.awt.Color(0, 51, 153));
        Secretarios_bt.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Secretarios_bt.setForeground(new java.awt.Color(255, 255, 255));
        Secretarios_bt.setText("Registrar secretaria");
        Secretarios_bt.setToolTipText("");
        Secretarios_bt.setBorder(new javax.swing.border.MatteBorder(null));
        Secretarios_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Secretarios_btActionPerformed(evt);
            }
        });
        getContentPane().add(Secretarios_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 150, 30));

        Volver_bt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Volver_bt.setText("Cerrar sesión");
        Volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_btActionPerformed(evt);
            }
        });
        getContentPane().add(Volver_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 140, 30));

        Bitacora.setBackground(new java.awt.Color(204, 204, 204));
        Bitacora.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Bitacora.setText("Bitacora");
        Bitacora.setBorder(new javax.swing.border.MatteBorder(null));
        Bitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BitacoraActionPerformed(evt);
            }
        });
        getContentPane().add(Bitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 80, 30));

        Lista_Trimestral.setBackground(new java.awt.Color(0, 51, 153));
        Lista_Trimestral.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Lista_Trimestral.setForeground(new java.awt.Color(255, 255, 255));
        Lista_Trimestral.setText("Listas Trimestrales");
        Lista_Trimestral.setBorder(new javax.swing.border.MatteBorder(null));
        Lista_Trimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_TrimestralActionPerformed(evt);
            }
        });
        getContentPane().add(Lista_Trimestral, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, 30));

        Datos_Estadisticos_.setBackground(new java.awt.Color(0, 51, 153));
        Datos_Estadisticos_.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Datos_Estadisticos_.setForeground(new java.awt.Color(255, 255, 255));
        Datos_Estadisticos_.setText("Estadisticas");
        Datos_Estadisticos_.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(Datos_Estadisticos_, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, 30));

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel23.setText("ESC. PRIM. Arcoiris");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Respaldo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, -1, -1));

        Respaldo_.setBackground(new java.awt.Color(204, 204, 204));
        Respaldo_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_respaldo.png"))); // NOI18N
        getContentPane().add(Respaldo_, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 60, 50));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Menu Principal");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 280, 60));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic", 3, 36)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Bienvenido");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 210, 70));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acciones rapidas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secre.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 120, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/direc.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 990, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void setFormLogin(FormLogin FormLogin)
    {
        this.FormLogin = FormLogin;
    }
    
    private void Alumnos_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alumnos_btActionPerformed
     FormFiltrarAlumnos formFiltrar = new FormFiltrarAlumnos();
    
    // Mostrar la ventana
    formFiltrar.setVisible(true);
    formFiltrar.setLocationRelativeTo(null); // Centrar en pantalla

    // Cerrar (u ocultar) el formulario actual si deseas
    this.dispose();
        
        
    }//GEN-LAST:event_Alumnos_btActionPerformed

    private void Secretarios_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Secretarios_btActionPerformed
        FormSecretarios ObjFormSecretarios = new FormSecretarios();
        ObjFormSecretarios.setFormMenu(this);
        ObjFormSecretarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Secretarios_btActionPerformed

    private void Volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_btActionPerformed
        FormLogin.setVisible(true);
        
        try 
        {
            FormLogin.conexionGlobal.IniciarConexion().close();
        } 
        catch (SQLException ex) 
        {
            System.getLogger(FormMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_Volver_btActionPerformed

    private void Generar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar_btActionPerformed
        FormGenerarBoletas ObjFormGenerarBoletas = new FormGenerarBoletas();
        ObjFormGenerarBoletas.setFormMenu(this);
        ObjFormGenerarBoletas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Generar_btActionPerformed

    private void BitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BitacoraActionPerformed
       
    }//GEN-LAST:event_BitacoraActionPerformed

    private void Lista_TrimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_TrimestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista_TrimestralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alumnos_bt;
    public javax.swing.JButton Bitacora;
    private javax.swing.JButton Datos_Estadisticos_;
    private javax.swing.JButton Generar_bt;
    private javax.swing.JButton Lista_Trimestral;
    public javax.swing.JButton Respaldo_;
    private javax.swing.JButton Secretarios_bt;
    private javax.swing.JButton Volver_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
