/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.GenerarBoletaControlador;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan De la Rosa
 */
public class FormGenerarBoletas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormGenerarBoletas.class.getName());
    private FormMenu FormMenu;
    private FormFiltrarAlumnos FormFiltrarAlumnos; 
    
    /**
     * Creates new form FormGenerarBoletas
     */
    public FormGenerarBoletas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Generar_bt = new javax.swing.JButton();
        Volver_bt = new javax.swing.JButton();
        Nombre_A = new javax.swing.JTextField();
        Apellidos_A = new javax.swing.JTextField();
        Curp = new javax.swing.JTextField();
        Grupo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Maestro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Generar_bt.setText("Generar Boleta (Beta)");
        Generar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar_btActionPerformed(evt);
            }
        });
        getContentPane().add(Generar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        Volver_bt.setText("Volver");
        Volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_btActionPerformed(evt);
            }
        });
        getContentPane().add(Volver_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 139, -1));

        Nombre_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_AActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, -1));
        getContentPane().add(Apellidos_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 210, -1));
        getContentPane().add(Curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, -1));

        Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupoActionPerformed(evt);
            }
        });
        getContentPane().add(Grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 60, -1));

        jLabel1.setText("Nombre: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setText("Apellidos: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setText("Grupo: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel4.setText("CURP: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setText("Maestro: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        getContentPane().add(Maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Generar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar_btActionPerformed
        GenerarBoletaControlador boleta = new GenerarBoletaControlador();
        
        try {
            // Llamar al método que genera el PDF
            boleta.GenerarBoleta();
            // El JOptionPane de éxito ya está dentro de GenerarBoleta()
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, 
                "Error al generar el PDF: Archivo no encontrado. Asegúrate de que el directorio 'Reportes' exista y no esté en uso. \n" + ex.getMessage(), 
                "Error de Archivo", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Ocurrió un error inesperado al generar la boleta: " + ex.getMessage(), 
                "Error Desconocido", 
                JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_Generar_btActionPerformed

    private void Volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_btActionPerformed
      this.dispose();
 
    }//GEN-LAST:event_Volver_btActionPerformed

    private void GrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrupoActionPerformed

    private void Nombre_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_AActionPerformed

    public void setFormMenu(FormMenu FormMenu)
    {
        this.FormMenu = FormMenu;
    }
    
    public void setDatosAlumno(String nombre, String apellido, String curp, String grupo, String maestro) {
    // Aquí puedes mostrar los datos en etiquetas o campos
    Nombre_A.setText(nombre);
    Apellidos_A.setText(apellido);
    Curp.setText(curp);
    Grupo.setText(grupo);
    Maestro.setText(maestro);
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormGenerarBoletas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidos_A;
    private javax.swing.JTextField Curp;
    private javax.swing.JButton Generar_bt;
    private javax.swing.JTextField Grupo;
    private javax.swing.JTextField Maestro;
    private javax.swing.JTextField Nombre_A;
    private javax.swing.JButton Volver_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

   
}
