/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.AlumnoControlador;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static vistas.FormLogin.conexionGlobal;
import vistas.FormAlumnosD;
import vistas.FormMenu;

/**
 *
 * @author Ivan De la Rosa
 */
public class FormFiltrarAlumnos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormFiltrarAlumnos.class.getName());
    private FormMenu FormMenu;
    private FormFiltrarAlumnos formFiltrarAlumnos;
    /**
     * Creates new form FormFiltrarAlumnos
     */
    public FormFiltrarAlumnos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
         if(conexionGlobal.RegresarUsuario().matches("^((?!director).)*$"))
        {
           
            
            
        }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by te Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Grupo_tb = new javax.swing.JTextField();
        Filtrar_bt = new javax.swing.JButton();
        Cerrar_bt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Consultar_tb = new javax.swing.JButton();
        nombre_maestro = new java.awt.TextField();
        grupo_n = new java.awt.TextField();
        Inscribir_tb = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        materias_tb = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_bt = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ESC. PRIM. Arcoiris");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Datos del alumno: ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texto.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filtrado de alumnos");
        setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grupo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Grupo_tb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Grupo_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grupo_tbActionPerformed(evt);
            }
        });
        getContentPane().add(Grupo_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, -1));

        Filtrar_bt.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Filtrar_bt.setText("Filtrar");
        Filtrar_bt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Filtrar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtrar_btActionPerformed(evt);
            }
        });
        getContentPane().add(Filtrar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 80, -1));

        Cerrar_bt.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Cerrar_bt.setText("Cerrar");
        Cerrar_bt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cerrar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_btActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Docente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Consultar_tb.setText("Consultar");
        Consultar_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_tbActionPerformed(evt);
            }
        });
        getContentPane().add(Consultar_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        nombre_maestro.setEditable(false);
        getContentPane().add(nombre_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 260, 20));

        grupo_n.setEditable(false);
        grupo_n.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        grupo_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupo_nActionPerformed(evt);
            }
        });
        getContentPane().add(grupo_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 50, 40));

        Inscribir_tb.setText("Inscribir");
        Inscribir_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscribir_tbActionPerformed(evt);
            }
        });
        getContentPane().add(Inscribir_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jScrollPane3.setBorder(null);

        materias_tb.setBackground(javax.swing.UIManager.getDefaults().getColor("Viewport.background"));
        materias_tb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        materias_tb.setForeground(new java.awt.Color(255, 255, 255));
        materias_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "MATERIAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(materias_tb);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 180, 190));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        tabla_bt.setAutoCreateRowSorter(true);
        tabla_bt.setBackground(new java.awt.Color(81, 111, 156));
        tabla_bt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabla_bt.setForeground(new java.awt.Color(255, 255, 255));
        tabla_bt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.Lista", "Nombre", "Apellidos", "CURP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_bt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 510, 220));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Alumnos Ingresados");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 380));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texto.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -10, 900, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents


public void refrescarTabla() {
    AlumnoControlador controlador = new AlumnoControlador();
    controlador.FiltrarAlumnos((Connection) FormLogin.conexionGlobal, 
        tabla_bt, 
        Grupo_tb, 
        grupo_n, 
        nombre_maestro, 
        materias_tb
    );
}




    private void Filtrar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtrar_btActionPerformed
        AlumnoControlador ObjAlumnoControlador = new AlumnoControlador();
        
        String grupoTexto = Grupo_tb.getText().trim();
         if (grupoTexto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un grupo para filtrar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
        } 
       ObjAlumnoControlador.FiltrarAlumnos(FormLogin.conexionGlobal.IniciarConexion(), tabla_bt, Grupo_tb,grupo_n,nombre_maestro, materias_tb );
       refrescarTabla();
    }//GEN-LAST:event_Filtrar_btActionPerformed

    private void Cerrar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_btActionPerformed
        this.setVisible(false); 
        FormMenu.setVisible(true);   
    }//GEN-LAST:event_Cerrar_btActionPerformed

    private void Grupo_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grupo_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grupo_tbActionPerformed

    private void grupo_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupo_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupo_nActionPerformed

    private void Inscribir_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscribir_tbActionPerformed
         FormAlumnosD formAlumnosD = new FormAlumnosD();
        
        // Hacerlo visible y centrar en pantalla
        formAlumnosD.setVisible(true);
        formAlumnosD.setLocationRelativeTo(null);   
    }//GEN-LAST:event_Inscribir_tbActionPerformed

    private void Consultar_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_tbActionPerformed
        int fila = tabla_bt.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un alumno de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Obtener el CURP de la fila seleccionada (columna 3 en tu tabla)
    String curpSeleccionado = tabla_bt.getValueAt(fila, 3).toString();

    // Crear el formulario destino
    FormAlumnosD formAlumnosD = new FormAlumnosD();

    // Llamar al controlador para cargar los datos desde la BD
    AlumnoControlador controlador = new AlumnoControlador();
    controlador.CargarAlumnoPorCURP(
        FormLogin.conexionGlobal.IniciarConexion(),
        curpSeleccionado,
        formAlumnosD.ID_tb,
        formAlumnosD.CURP_tb,
        formAlumnosD.Nombre_tb,
        formAlumnosD.Apellido_tb,
        formAlumnosD.fecha_bt,
        formAlumnosD.Edad_tb,
        formAlumnosD.Genero_tb,
        formAlumnosD.NombreP_tb,
        formAlumnosD.ApellidoP_tb,
        formAlumnosD.CorreoP_tb,
        formAlumnosD.TelefonoP_tb,
        formAlumnosD.Grupo_tb
    );

    // Mostrar el formulario centrado
    formAlumnosD.setVisible(true);
    formAlumnosD.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultar_tbActionPerformed

    /**
     * @param args the command line arguments
     */
    
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormFiltrarAlumnos().setVisible(true));
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        
            modelo.addColumn("No.Lista");
            modelo.addColumn("Apellidos");
            modelo.addColumn("Nombre");
            modelo.addColumn("CURP");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar_bt;
    private javax.swing.JButton Consultar_tb;
    private javax.swing.JButton Filtrar_bt;
    private javax.swing.JTextField Grupo_tb;
    private javax.swing.JButton Inscribir_tb;
    private java.awt.TextField grupo_n;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable materias_tb;
    private java.awt.TextField nombre_maestro;
    private javax.swing.JTable tabla_bt;
    // End of variables declaration//GEN-END:variables

    void setForm3(FormAlumnosD aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setFormMenu(FormMenu aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setForm1(FormMenu aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    


}
