/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import conexion.Conexion;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.JTextComponent;
import vistas.FormMenu;



/**
 *
 * @author Ivan De la Rosa
 */
public class FormLogin extends javax.swing.JFrame {
    
    public static Conexion conexionGlobal;
    private int intentosFallidos = 0;


    /**
     * Creates new form Login
     */
    public FormLogin() 
    {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        limitarCaracteres(Clave_tb, 15);
        limitarCaracteres(Usuario_tb, 15);
        //this.setSize(new Dimension(700,500));
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Usuario_tb = new javax.swing.JTextField();
        Ingresar_bt = new javax.swing.JButton();
        Salir_bt = new javax.swing.JButton();
        Mostrar_cb = new javax.swing.JCheckBox();
        Clave_tb = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_tbActionPerformed(evt);
            }
        });
        jPanel1.add(Usuario_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, -1));

        Ingresar_bt.setText("Ingresar");
        Ingresar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_btActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        Salir_bt.setText("Salir");
        Salir_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_btActionPerformed(evt);
            }
        });
        jPanel1.add(Salir_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        Mostrar_cb.setText("Mostrar Contraseña");
        Mostrar_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_cbActionPerformed(evt);
            }
        });
        jPanel1.add(Mostrar_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        Clave_tb.setEchoChar('*');
        Clave_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clave_tbActionPerformed(evt);
            }
        });
        Clave_tb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Clave_tbKeyPressed(evt);
            }
        });
        jPanel1.add(Clave_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicion de sesion_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void limitarCaracteres(JTextComponent campo, int maxCaracteres) {
    Document doc = campo.getDocument();
    if (doc instanceof AbstractDocument) {
        ((AbstractDocument) doc).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr)
                    throws BadLocationException {
                if ((fb.getDocument().getLength() + string.length()) <= maxCaracteres) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                if ((fb.getDocument().getLength() - length + text.length()) <= maxCaracteres) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }
}

        
    private void Clave_tbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Clave_tbKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            if (Clave_tb.getPassword().length > 0)
            {
                Ingresar_bt.doClick(); // Ejecutar la acciÃ³n del botÃ³n
            }
        }
    }//GEN-LAST:event_Clave_tbKeyPressed

    private void Mostrar_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_cbActionPerformed
        if (Mostrar_cb.isSelected())
        {
            Clave_tb.setEchoChar((char)0);
        }
        else
        {
            Clave_tb.setEchoChar('*');
        }
    }//GEN-LAST:event_Mostrar_cbActionPerformed

    private void Salir_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_btActionPerformed

        System.exit(0);
    }//GEN-LAST:event_Salir_btActionPerformed

    private void Ingresar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_btActionPerformed
       String clave = new String(Clave_tb.getPassword()).trim();
        String usuario = Usuario_tb.getText().trim();

        conexionGlobal = new Conexion();
        conexionGlobal.ObtenerUsuario(usuario, clave);
        conexionGlobal.IniciarConexion();

        if (conexionGlobal.ValidarConexion()) {
            
            FormMenu ObjFormMenu = new FormMenu();
            ObjFormMenu.setFormLogin(this);
            ObjFormMenu.setVisible(true);
            this.setVisible(false);
            intentosFallidos = 0; 
        } else {
            intentosFallidos++;
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Usuario o contraseña incorrectos.\nIntento " + intentosFallidos + " de 3.", 
                "Error de inicio de sesión", 
                javax.swing.JOptionPane.ERROR_MESSAGE);

            // Si se superan los 3 intentos, se cierra el sistema
            if (intentosFallidos >= 3) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Has superado el número máximo de intentos.\nEl sistema se cerrará.", 
                    "Acceso bloqueado", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            }
        }
    }//GEN-LAST:event_Ingresar_btActionPerformed

    private void Usuario_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_tbActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_tbActionPerformed

    private void Clave_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clave_tbActionPerformed
     
        // TODO add your handling code here:
    }//GEN-LAST:event_Clave_tbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLogin().setVisible(true));
         
        //new FormLogin().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Clave_tb;
    private javax.swing.JButton Ingresar_bt;
    private javax.swing.JCheckBox Mostrar_cb;
    private javax.swing.JButton Salir_bt;
    private javax.swing.JTextField Usuario_tb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
