/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.AlumnoControlador;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.JTextComponent;
import vistas.FormGenerarBoletas;
import static vistas.FormLogin.conexionGlobal;
/**
 *
 * @author Ivan De la Rosa
 */
public class FormAlumnosD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAlumnosD.class.getName());
    private FormFiltrarAlumnos formFiltrarAlumnos;
    
public void setFormFiltrarAlumnos(FormFiltrarAlumnos formFiltrarAlumnos) {
    this.formFiltrarAlumnos = formFiltrarAlumnos;
}
   
    
    /**
     * Creates new form FormSecretarios
     */
    public FormAlumnosD() 
    {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        limitarCaracteres(ApellidoP_tb, 25);
        limitarCaracteres(Apellido_tb, 30);
        limitarCaracteres(CURP_tb, 18);
        limitarCaracteres(CorreoP_tb, 30);
        limitarCaracteres(Edad_tb, 2);
        //limitarCaracteres(Genero_tb, 10); 
        limitarCaracteres(NombreP_tb, 25);
        limitarCaracteres(Nombre_tb, 25);
        limitarCaracteres(TelefonoP_tb, 10);
         if(conexionGlobal.RegresarUsuario().matches("^((?!director).)*$"))
        {
           Eliminar_bt.setVisible(false);
            Modificar_bt.setVisible(false);    
        }  
        // Restaurar color cuando el usuario escribe
        JTextComponent[] camposColor = {
            CURP_tb, Nombre_tb, Apellido_tb, fecha_bt, Edad_tb,
            NombreP_tb, ApellidoP_tb, CorreoP_tb, TelefonoP_tb, Grupo_tb
        };

        for (JTextComponent campo : camposColor) {
            campo.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    campo.setBackground(java.awt.Color.WHITE);
                }
            });
        }

        // ComboBox vuelve a blanco si se cambia selección
        Genero_tb.addActionListener(e -> Genero_tb.setBackground(java.awt.Color.WHITE));

        
        AlumnoControlador ObjAlumnoControlador = new AlumnoControlador();
        if (FormLogin.conexionGlobal != null && FormLogin.conexionGlobal.ValidarConexion()) 
        {
           
        } 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Edad_tb = new javax.swing.JTextField();
        Nombre_tb = new javax.swing.JTextField();
        Apellido_tb = new javax.swing.JTextField();
        ApellidoP_tb = new javax.swing.JTextField();
        NombreP_tb = new javax.swing.JTextField();
        Insertar_bt = new javax.swing.JButton();
        Modificar_bt = new javax.swing.JButton();
        Volver_bt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CorreoP_tb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TelefonoP_tb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Grupo_tb = new javax.swing.JTextField();
        CURP_tb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Eliminar_bt = new javax.swing.JButton();
        Genero_tb = new javax.swing.JComboBox<>();
        fecha_bt = new javax.swing.JTextField();
        Boleta_tb = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ID_tb = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumnos");

        jPanel1.setBackground(new java.awt.Color(97, 93, 186));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Edad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Género:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Nombre del tutor:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Apellido del tutor:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        Edad_tb.setEditable(false);
        jPanel1.add(Edad_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 80, -1));
        jPanel1.add(Nombre_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 150, -1));
        jPanel1.add(Apellido_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, -1));
        jPanel1.add(ApellidoP_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 150, -1));
        jPanel1.add(NombreP_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 150, -1));

        Insertar_bt.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Insertar_bt.setText("Insertar");
        Insertar_bt.setToolTipText("");
        Insertar_bt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Insertar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insertar_btActionPerformed(evt);
            }
        });
        jPanel1.add(Insertar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 170, -1));

        Modificar_bt.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Modificar_bt.setText("Modificar");
        Modificar_bt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Modificar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_btActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 170, -1));

        Volver_bt.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Volver_bt.setText("Volver");
        Volver_bt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_btActionPerformed(evt);
            }
        });
        jPanel1.add(Volver_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Correo del tutor:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));
        jPanel1.add(CorreoP_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Teléfono del tutor:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        TelefonoP_tb.setToolTipText("10");
        jPanel1.add(TelefonoP_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Grupo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        Grupo_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grupo_tbActionPerformed(evt);
            }
        });
        jPanel1.add(Grupo_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 150, -1));
        jPanel1.add(CURP_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("CURP:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        Eliminar_bt.setText("Eliminar");
        Eliminar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_btActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 130, -1));

        Genero_tb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Masculino", "Femenino" }));
        jPanel1.add(Genero_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 150, -1));

        fecha_bt.setEditable(false);
        fecha_bt.setToolTipText("");
        jPanel1.add(fecha_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, -1));

        Boleta_tb.setText("Boleta");
        Boleta_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boleta_tbActionPerformed(evt);
            }
        });
        jPanel1.add(Boleta_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Fecha de nacimiento:");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 170, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Datos del alumno: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Datos del tutor: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Alumno: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        ID_tb.setEditable(false);
        ID_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_tbActionPerformed(evt);
            }
        });
        jPanel1.add(ID_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 150, -1));

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ESC. PRIM. Arcoiris");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12.png"))); // NOI18N
        jLabel17.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jLabel17.setFocusable(false);
        jLabel17.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel17.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel17.setName(""); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabel17.setRequestFocusEnabled(false);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 490, 530));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texto.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-560, -20, 1370, 740));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Datos del alumno: ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Datos del alumno: ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void limitarCaracteres(JTextComponent campo, int maxCaracteres) {
    Document doc = campo.getDocument();
    if (doc instanceof AbstractDocument) {
        ((AbstractDocument) doc).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr)
                    throws BadLocationException {
                if ((fb.getDocument().getLength() + string.length()) <= maxCaracteres) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                if ((fb.getDocument().getLength() - length + text.length()) <= maxCaracteres) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }
}
    
  
    
    private void Insertar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insertar_btActionPerformed
        AlumnoControlador ObjAlumnoControlador = new AlumnoControlador();
        ObjAlumnoControlador.InsertarAlumno(FormLogin.conexionGlobal.IniciarConexion(), CURP_tb, Nombre_tb, Apellido_tb, fecha_bt,Edad_tb, Genero_tb, NombreP_tb, ApellidoP_tb, CorreoP_tb, TelefonoP_tb, Grupo_tb);
         boolean valido = true;

    // Validar campos vacíos
    JTextComponent[] campos = {
        CURP_tb, Nombre_tb, Apellido_tb, 
        NombreP_tb, ApellidoP_tb, CorreoP_tb, TelefonoP_tb, 
    };

    for (JTextComponent campo : campos) {
        if (campo.getText().trim().isEmpty()) {
            campo.setBackground(new java.awt.Color(255, 102, 102)); // rojo claro
            valido = false;
        } else {
            campo.setBackground(java.awt.Color.WHITE);
        }
    }

    if (Genero_tb.getSelectedIndex() == 0) {
        Genero_tb.setBackground(new java.awt.Color(255, 102, 102));
        valido = false;
    } else {
        Genero_tb.setBackground(java.awt.Color.WHITE);
    }

    if (!valido) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos obligatorios.", "Campos vacíos", JOptionPane.ERROR_MESSAGE);
        return;
    }

   // AlumnoControlador ObjAlumnoControlador = new AlumnoControlador();
    ObjAlumnoControlador.InsertarAlumno(
        FormLogin.conexionGlobal.IniciarConexion(), 
        CURP_tb, Nombre_tb, Apellido_tb, fecha_bt, Edad_tb, Genero_tb, 
        NombreP_tb, ApellidoP_tb, CorreoP_tb, TelefonoP_tb, Grupo_tb
    );

  //  JOptionPane.showMessageDialog(this, "Alumno insertado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_Insertar_btActionPerformed

    private void Modificar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_btActionPerformed
        AlumnoControlador ObjAlumnoControlador = new AlumnoControlador();
        ObjAlumnoControlador.ModificarAlumno(FormLogin.conexionGlobal.IniciarConexion(), ID_tb, CURP_tb, Nombre_tb, Apellido_tb, fecha_bt,Edad_tb, Genero_tb, NombreP_tb, ApellidoP_tb, CorreoP_tb, TelefonoP_tb, Grupo_tb);
   
    }//GEN-LAST:event_Modificar_btActionPerformed

    private void Volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_btActionPerformed
      this.dispose();
        
    }//GEN-LAST:event_Volver_btActionPerformed

    private void Grupo_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grupo_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grupo_tbActionPerformed

    private void ID_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_tbActionPerformed

    private void Eliminar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_btActionPerformed

        AlumnoControlador controlador = new AlumnoControlador();

    controlador.EliminarAlumno(FormLogin.conexionGlobal.IniciarConexion(), ID_tb);

    // 🔁 Refrescar la tabla del otro formulario (si está conectado)
    if (formFiltrarAlumnos != null) {
        formFiltrarAlumnos.refrescarTabla();
    }
    }//GEN-LAST:event_Eliminar_btActionPerformed

    private void Boleta_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boleta_tbActionPerformed
         FormGenerarBoletas formBoleta = new FormGenerarBoletas();
        
        // Hacerlo visible y centrar en pantalla
        formBoleta.setVisible(true);
        formBoleta.setLocationRelativeTo(null); 
    }//GEN-LAST:event_Boleta_tbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormAlumnosD().setVisible(true));
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ApellidoP_tb;
    public javax.swing.JTextField Apellido_tb;
    private javax.swing.JButton Boleta_tb;
    public javax.swing.JTextField CURP_tb;
    public javax.swing.JTextField CorreoP_tb;
    public javax.swing.JTextField Edad_tb;
    private javax.swing.JButton Eliminar_bt;
    public javax.swing.JComboBox<String> Genero_tb;
    public javax.swing.JTextField Grupo_tb;
    public javax.swing.JTextField ID_tb;
    private javax.swing.JButton Insertar_bt;
    private javax.swing.JButton Modificar_bt;
    public javax.swing.JTextField NombreP_tb;
    public javax.swing.JTextField Nombre_tb;
    public javax.swing.JTextField TelefonoP_tb;
    private javax.swing.JButton Volver_bt;
    public javax.swing.JTextField fecha_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 
}
