/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package vistas;
import java.sql.SQLException;
import static vistas.FormLogin.conexionGlobal;

/**
 *
 * @author Benny Brian
 */
public class FromMenuSecre extends javax.swing.JPanel implements java.beans.Customizer {
      private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromMenuSecre.class.getName());
    private FormLogin FormLogin;
    //private Object bean;

    /**
     * Creates new customizer NewCustomizer
     */
    public FromMenuSecre() {
        initComponents();
    }
    
    public void setObject(Object bean) {
      //  this.bean = bean;
    }
    
    public void setFormLogin(FormLogin FormLogin)
    {
        this.FormLogin = FormLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alumnos_bt = new javax.swing.JButton();
        Generar_bt = new javax.swing.JButton();
        Datos_Estadisticos_ = new javax.swing.JButton();
        Lista_Trimestral = new javax.swing.JButton();
        Volver_bt = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Alumnos_bt.setBackground(new java.awt.Color(0, 0, 153));
        Alumnos_bt.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Alumnos_bt.setForeground(new java.awt.Color(255, 255, 255));
        Alumnos_bt.setText("Registrar Alumnos");
        Alumnos_bt.setToolTipText("");
        Alumnos_bt.setBorder(new javax.swing.border.MatteBorder(null));
        Alumnos_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alumnos_btActionPerformed(evt);
            }
        });
        add(Alumnos_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        Generar_bt.setBackground(new java.awt.Color(0, 0, 153));
        Generar_bt.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Generar_bt.setForeground(new java.awt.Color(255, 255, 255));
        Generar_bt.setText("Boletas");
        Generar_bt.setBorder(new javax.swing.border.MatteBorder(null));
        Generar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar_btActionPerformed(evt);
            }
        });
        add(Generar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, 30));

        Datos_Estadisticos_.setBackground(new java.awt.Color(0, 0, 153));
        Datos_Estadisticos_.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Datos_Estadisticos_.setForeground(new java.awt.Color(255, 255, 255));
        Datos_Estadisticos_.setText("Datos estadisticos");
        Datos_Estadisticos_.setBorder(new javax.swing.border.MatteBorder(null));
        Datos_Estadisticos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Datos_Estadisticos_ActionPerformed(evt);
            }
        });
        add(Datos_Estadisticos_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 140, 30));

        Lista_Trimestral.setBackground(new java.awt.Color(0, 0, 153));
        Lista_Trimestral.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Lista_Trimestral.setForeground(new java.awt.Color(255, 255, 255));
        Lista_Trimestral.setText("Listas Trimestrales");
        Lista_Trimestral.setBorder(new javax.swing.border.MatteBorder(null));
        Lista_Trimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_TrimestralActionPerformed(evt);
            }
        });
        add(Lista_Trimestral, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, 30));

        Volver_bt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Volver_bt.setText("Cerrar sesión");
        Volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_btActionPerformed(evt);
            }
        });
        add(Volver_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 140, -1));

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel23.setText("ESC. PRIM. Arcoiris");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Menu Principal");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 280, 60));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic", 3, 36)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Bienvenido");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 210, 70));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acciones rapidas:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secre.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 990, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void Alumnos_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alumnos_btActionPerformed
        
    }//GEN-LAST:event_Alumnos_btActionPerformed

    private void Generar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar_btActionPerformed
        
    }//GEN-LAST:event_Generar_btActionPerformed

    private void Lista_TrimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_TrimestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista_TrimestralActionPerformed

    private void Volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_btActionPerformed
      FormLogin.setVisible(true);
        
        try 
        {
            FormLogin.conexionGlobal.IniciarConexion().close();
        } 
        catch (SQLException ex) 
        {
            System.getLogger(FormMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_Volver_btActionPerformed

    private void Datos_Estadisticos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Datos_Estadisticos_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Datos_Estadisticos_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Alumnos_bt;
    public javax.swing.JButton Datos_Estadisticos_;
    public javax.swing.JButton Generar_bt;
    public javax.swing.JButton Lista_Trimestral;
    public javax.swing.JButton Volver_bt;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
